# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # main 브랜치에서 Push 트리거
  pull_request:
    branches: [ "main" ] # main 브랜치에서 Pull Request가 생성되면 트리거

# Github의 데이터 가져와서 Build 진행 => Iaas+Paas => OS가 필요
jobs:
  build:

    runs-on: ubuntu-latest # Gihub Actions에서 실행할 운영체제

    steps: # 단계별로 실행되는 workflow
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
#    - name: Build with Maven
#      run: |
#        mvn clean package \
#        -DskipTests \
#        -f ./deploy003_SpringMVC/pom.xml

    - name : Deploy to Tomcat Server
      env:
        TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }} #git secret의 TOMCAT 사용자명 run에서 사용
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }} #git secret의 TOMCAT 비밀번호 run에서 사용
        TOMCAT_URL: 'https://ecology-rendering-scuttle.ngrok-free.dev/manager/text'
      
      run: |
        mvn tomcat:redeploy \
          -Dmaven.tomcat.url=$TOMCAT_URL \
          -Dmaven.tomcat.username=$TOMCAT_USERNAME \
          -Dmaven.tomcat.password=$TOMCAT_PASSWORD \
          -DskipTests \
          -f ./pom.xml